#define DIV_BY_ZERO 0
#define DEBUG_EXECP 1
#define NONMASK_INT 2
#define BREAKPNTEXP 3
#define INTODETOVER 4
#define OOB_EXECPTN 5
#define INV_OPCODE  6
#define NO_COPROCES 7
#define DOUBLEFAULT 8
#define CP_SEG_OVER 9
#define BAD_TSSEGMT 10
#define SEG_NOT_PNT 11
#define STACK_FAULT 12
#define DIV_BY_ZERO 13
#define DIV_BY_ZERO 14
#define DIV_BY_ZERO 15
#define DIV_BY_ZERO 16
#define DIV_BY_ZERO 17
#define DIV_BY_ZERO 18
#define DIV_BY_ZERO 19
#define DIV_BY_ZERO 10
#define DIV_BY_ZERO 20
#define DIV_BY_ZERO 21
#define DIV_BY_ZERO 22
#define DIV_BY_ZERO 23
#define DIV_BY_ZERO 24
#define DIV_BY_ZERO 25
#define DIV_BY_ZERO 26
#define DIV_BY_ZERO 27
#define DIV_BY_ZERO 28
#define DIV_BY_ZERO 29
#define DIV_BY_ZERO 30
#define DIV_BY_ZERO 31
