#ifndef CHRONOS_VERSION_H
#define CHRONOS_VERSION_H


#define CHRONOS_VERSION_MAJOR 1
#define CHRONOS_VERSION_MINOR 0
#define CHRONOS_VERSION_REVISION 0
#define CHRONOS_VERSION_PATCH 0

#define DEVELOPMEMT_MODE 1
#define CHRONOS_ARCH "x86"

#endif
